---
# tasks file for flens
- name: Copy Telegraf from file [RHEL/CentOS]
  copy:
    src: telegraf-1.17.3-1.x86_64.rpm
    dest: /tmp

- name: Install Telegraf rpm from a local file
  yum:
    name: /tmp/telegraf-1.17.3-1.x86_64.rpm
    state: present
  register: flens_installed

- name: Copy config file
  copy:
    src: telegraf.conf.{{ ansible_hostname | lower }}
    dest: /etc/telegraf/telegraf.conf

- name: Copy linux config file
  copy:
    src: linux.conf.{{ ansible_hostname  | lower }}
    dest: /etc/telegraf/telegraf.d/linux.conf

- name: remove rpm file
  file:
    state: absent
    dest: /tmp/telegraf-1.17.3-1.x86_64.rpm

- name: Enable Telegraf
  service:
    name: telegraf
    enabled: yes
  changed_when: flens_installed
  notify:
    - "restart telegraf"
